### ISSUE TITLE
Bug: Unable to read your .nextplop.json file. So sad!

### ISSUE THREAD

**Issue by jesperordrup** [zackkrida/next-codegen#8]
When running 

`C:\Users\Jesper\Desktop\codegen>npx next-codegen`

I get

`Unable to read your .nextplop.json file. So sad!`

Which is so sad.

**Comment by zackkrida** [comment]
I'll let you know when this project is ready for testing! It's been completely rewritten locally and will be launching soon 😄

**Comment by zackkrida** [comment]
Hi @jesperordrup I've gone ahead and released `1.0.0` today! Go ahead and take a look.

**Comment by jesperordrup** [comment]
Thanks @zackkrida - I'll give it a go! 
(I've sent u an email)
